// JsFromRoutes CacheKey a92e257f9c352b085bb7f8b96530cdd9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/projects/:project_id/analyses'),
  new: /* #__PURE__ */ definePathHelper('get', '/projects/:project_id/analyses/new'),
}
