// JsFromRoutes CacheKey 3d8613bede0d6d26c37329e03d82d9f5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/projects'),
  new: /* #__PURE__ */ definePathHelper('get', '/projects/new'),
  show: /* #__PURE__ */ definePathHelper('get', '/projects/:id'),
}
