// JsFromRoutes CacheKey 1e50c99034964b49e91243ec7b61c7cb
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/projects'),
  new: /* #__PURE__ */ definePathHelper('get', '/projects/new'),
}
